<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Personnel;

class PersonnelTestSeeder extends Seeder
{
    public function run(): void
    {
        // Créer 5 employés de test
        $employes = [
            [
                'matricule' => 'EMP001',
                'nom' => 'Koné',
                'prenoms' => 'Mamadou',
                'date_naissance' => '1990-05-15',
                'lieu_naissance' => 'Abidjan',
                'nationalite' => 'Ivoirienne',
                'sexe' => 'M',
                'situation_matrimoniale' => 'Célibataire',
                'nb_enfants_charge' => 0,
                'telephone_principal' => '0712345678',
                'email_personnel' => 'kone.mamadou@kenam.com',
                'adresse_residence' => 'Abidjan, Cocody',
                'ville' => 'Abidjan',
                'type_piece' => 'CNI',
                'numero_piece' => 'CI123456789',
                'date_delivrance_piece' => '2020-01-15',
                'lieu_delivrance_piece' => 'Abidjan',
                'poste' => 'Chauffeur',
                'service' => 'Logistique',
                'categorie' => 'C',
                'type_contrat' => 'CDI',
                'date_embauche' => '2023-01-15',
                'salaire_base' => 150000,
                'nom_urgence' => 'Koné Adama',
                'telephone_urgence' => '0723456789',
                'lien_parente' => 'Frere',
                'statut' => 'ACTIF',
            ],
            [
                'matricule' => 'EMP002',
                'nom' => 'Touré',
                'prenoms' => 'Fatoumata',
                'date_naissance' => '1992-08-20',
                'lieu_naissance' => 'Yamoussoukro',
                'nationalite' => 'Ivoirienne',
                'sexe' => 'F',
                'situation_matrimoniale' => 'Mariée',
                'nb_enfants_charge' => 2,
                'telephone_principal' => '0734567890',
                'email_personnel' => 'toure.fatou@kenam.com',
                'adresse_residence' => 'Abidjan, Plateau',
                'ville' => 'Abidjan',
                'type_piece' => 'CNI',
                'numero_piece' => 'CI987654321',
                'date_delivrance_piece' => '2019-03-10',
                'lieu_delivrance_piece' => 'Yamoussoukro',
                'poste' => 'Secrétaire',
                'service' => 'Administration',
                'categorie' => 'B',
                'type_contrat' => 'CDI',
                'date_embauche' => '2022-06-01',
                'salaire_base' => 120000,
                'nom_urgence' => 'Touré Ibrahim',
                'telephone_urgence' => '0745678901',
                'lien_parente' => 'Mari',
                'statut' => 'ACTIF',
            ],
            [
                'matricule' => 'EMP003',
                'nom' => 'Ouattara',
                'prenoms' => 'Yao',
                'date_naissance' => '1988-12-10',
                'lieu_naissance' => 'Bouaké',
                'nationalite' => 'Ivoirienne',
                'sexe' => 'M',
                'situation_matrimoniale' => 'Marié',
                'nb_enfants_charge' => 3,
                'telephone_principal' => '0756789012',
                'email_personnel' => 'ouattara.yao@kenam.com',
                'adresse_residence' => 'Abidjan, Marcory',
                'ville' => 'Abidjan',
                'type_piece' => 'CNI',
                'numero_piece' => 'CI456789123',
                'date_delivrance_piece' => '2018-07-20',
                'lieu_delivrance_piece' => 'Bouaké',
                'poste' => 'Technicien',
                'service' => 'Maintenance',
                'categorie' => 'B',
                'type_contrat' => 'CDI',
                'date_embauche' => '2021-09-15',
                'salaire_base' => 180000,
                'nom_urgence' => 'Ouattara Awa',
                'telephone_urgence' => '0767890123',
                'lien_parente' => 'Epouse',
                'statut' => 'ACTIF',
            ],
            [
                'matricule' => 'EMP004',
                'nom' => 'Bamba',
                'prenoms' => 'Aminata',
                'date_naissance' => '1995-03-25',
                'lieu_naissance' => 'San Pedro',
                'nationalite' => 'Ivoirienne',
                'sexe' => 'F',
                'situation_matrimoniale' => 'Célibataire',
                'nb_enfants_charge' => 0,
                'telephone_principal' => '0768901234',
                'email_personnel' => 'bamba.aminata@kenam.com',
                'adresse_residence' => 'Abidjan, Treichville',
                'ville' => 'Abidjan',
                'type_piece' => 'CNI',
                'numero_piece' => 'CI789123456',
                'date_delivrance_piece' => '2021-11-05',
                'lieu_delivrance_piece' => 'San Pedro',
                'poste' => 'Comptable',
                'service' => 'Finance',
                'categorie' => 'A',
                'type_contrat' => 'CDI',
                'date_embauche' => '2023-02-01',
                'salaire_base' => 200000,
                'nom_urgence' => 'Bamba Kader',
                'telephone_urgence' => '0778901234',
                'lien_parente' => 'Frere',
                'statut' => 'ACTIF',
            ],
            [
                'matricule' => 'EMP005',
                'nom' => 'Kouadio',
                'prenoms' => 'Jean-Claude',
                'date_naissance' => '1987-07-18',
                'lieu_naissance' => 'Gagnoa',
                'nationalite' => 'Ivoirienne',
                'sexe' => 'M',
                'situation_matrimoniale' => 'Marié',
                'nb_enfants_charge' => 1,
                'telephone_principal' => '0789012345',
                'email_personnel' => 'kouadio.jean@kenam.com',
                'adresse_residence' => 'Abidjan, Yopougon',
                'ville' => 'Abidjan',
                'type_piece' => 'CNI',
                'numero_piece' => 'CI321654987',
                'date_delivrance_piece' => '2017-04-12',
                'lieu_delivrance_piece' => 'Gagnoa',
                'poste' => 'Agent de sécurité',
                'service' => 'Sécurité',
                'categorie' => 'D',
                'type_contrat' => 'CDI',
                'date_embauche' => '2020-05-20',
                'salaire_base' => 100000,
                'nom_urgence' => 'Kouadio Marie',
                'telephone_urgence' => '0790123456',
                'lien_parente' => 'Epouse',
                'statut' => 'ACTIF',
            ],
        ];

        foreach ($employes as $employe) {
            // Ajouter les champs d'audit
            $employe['created_by'] = 2; // ID du premier utilisateur existant
            $employe['updated_by'] = 2;

            Personnel::create($employe);
        }

        $this->command->info('5 employés de test créés avec succès !');
    }
}
