<?php

return [
    'modules' => [
        'admin' => [
            'operations',
            'suivi',
            'validations',
            'reporting',
            'analyses',
            'audit',
            'settings',
            'comptabilite',
            'stock',
            'rh',
            'commercial',
            'fournisseurs',
            'notifications',
            'parc',
            'devis',
            'parametrage',
            'magasin',
            'entrepots',
            'materiel',
            'cost_control',
            'tresorerie',
            'agenda',
            'requetes',
            'profile',
        ],
        'superadmin' => ['*'],
        'manager' => [
            'dashboard',
            'comptabilite',
            'stock',
            'validations',
            'commercial',
            'fournisseurs',
            'notifications',
            'operations',
            'parc',
            'rh',
            'agent',
            'devis',
            'parametrage',
            'magasin',
            'entrepots',
            'materiel',
            'cost_control',
            'audit',
            'reporting',
            'analyses',
            'tresorerie',
            'agenda',
            'settings',
            'requetes',
        ],
        'tresorerie' => [
            'operations',
            'validations',
            'tresorerie',
        ],
        'commercial' => [
            'operations',
            'validations',
        ],
        'rh' => [
            'operations',
            'validations',
        ],
        'comptabilite' => [
            'operations',
            'validations',
            'comptabilite',
        ],
        'moderator' => [
            'dashboard', // À configurer selon les besoins
            'operations',
            'suivi',
            'validations',
            'notifications',
            'profile',
        ],
        'agent' => [
            'operations',
            'suivi',
            'validations',
            'notifications',
            'profile',
        ],
        'user' => [
            'operations',
            'suivi',
            'validations',
            'notifications',
            'profile',
        ],
    ],
];
